[package]
name = "seqrs"
version = "0.2.0"
authors = ["Christian <christian.jena@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
bio = "0.33.0"
bio-types = "0.11.0"