on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
      - name: Cargo build
        with:
          command: build

      - uses: actions-rs/cargo@v1
      - name: Run on 1200 amplicons
        with:
          command: run
          args: -- -g data/multifasta_v1200.fasta -p data/Primerfiles/V1200/nCoV-2019.bed 
      
      - uses: actions-rs/cargo@v1
      - name: Run on 400 amplicons
        with:
          command: run
          args: -- -g data/multifasta_v1200.fasta -p data/Primerfiles/V3/nCoV-2019.bed -r results-400.txt -a 400 

      - uses: actions-rs/cargo@v1
      - name: Clippy lint
        with:
          command: clippy
          args: -- -D warnings